### ISSUE TITLE
本地运行正常，放到服务器解析失败

### ISSUE THREAD

**Issue by Lw1244204021** [Suxiaoqinx/Netease_url#1]
链接：https://music.163.com/#/song?id=2109271842
本地run正常，能拿到数据
但是放到阿里云上，就拿不到啦：
jseg和jse信息如下，不知道是不是我的是香港的服务器的原因？

{'data': [{'id': 2109271842, 'url': None, 'br': 0, 'size': 0, 'md5': None, 'code': 404, 'expi': 1200, 'type': None, 'gain': 0.0, 'peak': None, 'fee': 0, 'uf': None, 'payed': 0, 'flag': 1544196, 'canExtend': False, 'freeTrialInfo': None, 'level': None, 'encodeType': None, 'channelLayout': None, 'freeTrialPrivilege': {'resConsumable': False, 'userConsumable': False, 'listenType': None, 'cannotListenReason': 1, 'playReason': None}, 'freeTimeTrialPrivilege': {'resConsumable': False, 'userConsumable': False, 'type': 0, 'remainTime': 0}, 'urlSource': 0, 'rightSource': 0, 'podcastCtrp': None, 'effectTypes': None, 'time': 0}], 'code': 200}

{'songs': [{'name': '句号', 'id': 2109271842, 'pst': 0, 't': 0, 'ar': [{'id': 36292385, 'name': '木夕', 'tns': [], 'alias': []}], 'alia': [], 'pop': 100.0, 'st': 0, 'rt': '', 'fee': 8, 'v': 7, 'crbt': None, 'cf': '', 'al': {'id': 181285340, 'name': '句号', 'picUrl': 'https://p2.music.126.net/SwUBZ7h4RJc02eYiwXn0DA==/109951169168272021.jpg', 'tns': [], 'pic_str': '109951169168272021', 'pic': 109951169168272021}, 'dt': 148000, 'h': {'br': 320002, 'fid': 0, 'size': 5922285, 'vd': 4570.0, 'sr': 48000}, 'm': {'br': 192002, 'fid': 0, 'size': 3553389, 'vd': 7202.0, 'sr': 48000}, 'l': {'br': 128002, 'fid': 0, 'size': 2368941, 'vd': 8967.0, 'sr': 48000}, 'sq': {'br': 681647, 'fid': 0, 'size': 12610472, 'vd': 4571.0, 'sr': 48000}, 'hr': {'br': 1418882, 'fid': 0, 'size': 26249321, 'vd': 4571.0, 'sr': 48000}, 'a': None, 'cd': '01', 'no': 1, 'rtUrl': None, 'ftype': 0, 'rtUrls': [], 'djId': 0, 'copyright': 0, 's_id': 0, 'mark': 17716748288, 'originCoverType': 1, 'originSongSimpleData': None, 'tagPicList': None, 'resourceState': True, 'version': 7, 'songJumpInfo': None, 'entertainmentTags': None, 'awardTags': None, 'single': 0, 'noCopyrightRcmd': None, 'mv': 0, 'mst': 9, 'cp': 0, 'rtype': 0, 'rurl': None, 'publishTime': 0}], 'privileges': [{'id': 2109271842, 'fee': 0, 'payed': 0, 'st': -100, 'pl': 0, 'dl': 0, 'sp': 7, 'cp': 1, 'subp': 1, 'cs': False, 'maxbr': 999000, 'fl': 0, 'toast': False, 'flag': 4, 'preSell': False, 'playMaxbr': 999000, 'downloadMaxbr': 999000, 'maxBrLevel': 'hires', 'playMaxBrLevel': 'hires', 'downloadMaxBrLevel': 'hires', 'plLevel': 'none', 'dlLevel': 'none', 'flLevel': 'none', 'rscl': 0, 'freeTrialPrivilege': {'resConsumable': False, 'userConsumable': False, 'listenType': None, 'cannotListenReason': 1, 'playReason': None}, 'rightSource': 0, 'chargeInfoList': [{'rate': 128000, 'chargeUrl': None, 'chargeMessage': None, 'chargeType': 0}, {'rate': 192000, 'chargeUrl': None, 'chargeMessage': None, 'chargeType': 0}, {'rate': 320000, 'chargeUrl': None, 'chargeMessage': None, 'chargeType': 0}, {'rate': 999000, 'chargeUrl': None, 'chargeMessage': None, 'chargeType': 1}, {'rate': 1999000, 'chargeUrl': None, 'chargeMessage': None, 'chargeType': 1}]}], 'code': 200}

**Comment by Suxiaoqinx** [comment]
song_names = "https://music.163.com/api/v3/song/detail"替换成

https://interface3.music.163.com/api/v3/song/detail看看能不能用

因为music.163.com是禁止海外用户访问的😅

**Comment by Suxiaoqinx** [comment]
song_names = "https://music.163.com/api/v3/song/detail"替换成

https://interface3.music.163.com/api/v3/song/detail看看能不能用

因为music.163.com是禁止海外用户访问的😅

**Comment by Lw1244204021** [comment]
> https://music.163.com/api/v3/song/detail 替换成
> 
> https://interface3.music.163.com/api/v3/song/detail
> 
> 看看能不能用
> 
> 因为music.163.com是禁止海外用户访问的😅

依然不行，可能只能境内访问了

**Comment by Suxiaoqinx** [comment]
> > https://music.163.com/api/v3/song/detail 替换成
> > 
> > https://interface3.music.163.com/api/v3/song/detail
> > 
> > 看看能不能用
> > 
> > 因为music.163.com是禁止海外用户访问的😅
> 
> 依然不行，可能只能境内访问了

我看你这是音频链接无法获取到 你将本地run的返回结果给我看看可以吗 加个QQ3074193836

**Comment by cgqhegl** [comment]
@Suxiaoqinx 没有办法加你QQ，搜索不到
